---
    -
        name: Configure nodes
        hosts: all
        become: true
        tasks:
            - import_tasks: configure-docker.yaml
            - import_tasks: configure-k8s.yaml
            -
                name: Copy the join command to server location
                copy:
                    src: "join_command.sh"
                    dest: "/tmp/join_command.sh"
                    mode: 0777
            -
                name: Join the node to cluster  # noqa: 301
                command:
                    cmd: sh /tmp/join_command.sh