-
    name: Install packages that allow to be access docker repositories over HTTPS
    apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
        force_apt_get: yes
    vars:
        packages:
            - apt-transport-https
            - ca-certificates
            - curl
            - gnupg-agent
            - software-properties-common
-
    name: Add Docker GPG Key
    apt_key:
        url: "https://download.docker.com/linux/ubuntu/gpg"
        state: present
-
    name: Install Docker repositories
    apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present
-
    name: Install Docker
    apt:
        name: docker-ce
        state: present
        update_cache: yes
        force_apt_get: yes
-
    name: Add vagrant user to docker group
    user:
        name: vagrant
        group: docker
-
    name: Enable Docker service
    systemd:
        name: docker
        enabled: yes
        state: started
-
    name: Enable Docker completions
    get_url:
        url: https://raw.githubusercontent.com/docker/docker-ce/master/components/cli/contrib/completion/bash/docker
        dest: /etc/bash_completion.d/docker.sh
